[general]
live_config_reload = true

[terminal.shell]
program = "zsh"

[window]
opacity = 0.95
dynamic_padding = false

[window.padding]
x = 0
y = 0

[scrolling]
history = 10000

[font]
size = 16.0

[font.offset]
x = 0
y = 0
